timezone: America/Los_Angeles
puid: 1001
guid: 1001

# Valheim server configurations
servers:
# note: Each server uses (+2) more ports above the connect port, so
# make sure to space them out appropriately

  - name: TacoTimeNW
    world: Dedicated
    port: 2456
    public: no
    auto_update: yes
    auto_update_schedule: "30 5 * * *"
    admins: 
      - '76561198011336370' # softtacowithbeef
    banned: []
    permitted: []
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66623666363365383337313335396633336166303830386634343039633462326662623565643439
      6339303838313238326161343163366262633339633931380a643563643961303632336664306231
      39663132306135386536386534323634613766303032326365623030303339376630663366383262
      6637393439613937370a643836313630393535636565373363663461326532386364386634653461
      30323964386364333730616339366336353730353935326631643865653134396139
    

  - name: Lerland
    world: Lerland
    port: 2459
    public: no
    auto_update: yes
    auto_update_schedule: "30 5 * * *"
    admins:
      - '76561197994970408' # ler
    banned: []
    permitted: []
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39646362393233393735356166636534366330376637376561656164663864653338636130663364
      3066346663313636393132656165313566303936326136620a326635633061643136343835366465
      38346334353136626362346532303930306230626534643234356362636639663235363138366664
      6665343130343235340a623264333366316263613233343530613736643733346361333362363538
      6432
